spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/GraphDB
    username: postgres
    password: ***
  graphql:
    graphiql:
      enabled: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
